# -*- mode: dockerfile -*-
FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

RUN apt-get update && \
    apt-get install -y wget python-dev gcc && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py

RUN pip install mxnet-cu100mkl --pre -i https://pypi.tuna.tsinghua.edu.cn/simple