# -*- mode: dockerfile -*-
FROM pistonyang/mxnet:base-cuda90
LABEL maintainer="pistonyang@gmail.com"

RUN pip3 install gluocv gluonfr \
    –no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple



