# -*- mode: dockerfile -*-
FROM pistonyang/mxnet:base-cu90
LABEL maintainer="pistonyang@gmail.com"

RUN pip3 install gluoncv --pre \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --no-cache-dir


